import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FronLayout from "@/Components/FronLayout/FronLayout";
import AppsProvider from "@/Components/AppsProvider/AppsProvider";
import Footer from "@/Components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen" suppressHydrationWarning>
        <AppsProvider>
          <FronLayout />

          <main className="flex-1 w-full">{children}</main>

          <Footer />
        </AppsProvider>
      </body>
    </html>
  );
}
